spring:
  application:
    name: "Validator Service"
server:
  port: 8081

application:
  debugEnabled: true

queue:
  url: "amqp://localhost:5672/%2f"
  username: "kion"
  password: "bunga"

persistence:
  url: "http://localhost:8082"
  username: "validator-api"
  password: "bunga"


crons:
  retryCheck: "*/30 * * * * *"
#  retryCheck: "0 0 1 * * ?" #every day at 1AM
