version: '2'
services:
  postgres:
    image: postgres
    container_name: db.kion.bunga.postgres
    domainname: db.kion.bunga.postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=payment_app
      - POSTGRES_USER=kion
      - POSTGRES_PASSWORD=bunga

  rabbit1:
      image: "rabbitmq:3-management"
      hostname: "rabbit1"
      environment:
        RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
        RABBITMQ_DEFAULT_USER: "kion"
        RABBITMQ_DEFAULT_PASS: "bunga"
        RABBITMQ_DEFAULT_VHOST: "/"
      ports:
        - "15672:15672"
        - "5672:5672"
      labels:
        NAME: "rabbitmq1"

  redis:
    image: redis
    container_name: db.kion.bunga.redis
    domainname: db.kion.bunga.redis
    ports:
      - "6379:6379"
