spring:
  application:
    name: "Persist Service"
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/payment_app
    driver-class-name: org.postgresql.Driver
    username: kion
    password: bunga
    hikari:
      leak-detection-threshold: 10000
      maximum-pool-size: 20
      minimumIdle: 4
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    show-sql: false
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.jdbc.lob.non_contextual_creation: true
  redis:
    host: "localhost"
    port: 6379

server:
  port: 8082

application:
  debugEnabled: true
  username: kion
  password: bunga


queue:
  url: "amqp://localhost:5672/%2f"
  username: "kion"
  password: "bunga"

