// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package com.kion.bunga.domain;

public final class Proto {
  private Proto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.kion.bunga.domain.TRANSACTION_STATUS}
   */
  public enum TRANSACTION_STATUS
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DONE = 0;</code>
     */
    DONE(0),
    /**
     * <code>DENIED = 1;</code>
     */
    DENIED(1),
    /**
     * <code>ALREADY_DONE = 2;</code>
     */
    ALREADY_DONE(2),
    /**
     * <code>RETRY = 3;</code>
     */
    RETRY(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>DONE = 0;</code>
     */
    public static final int DONE_VALUE = 0;
    /**
     * <code>DENIED = 1;</code>
     */
    public static final int DENIED_VALUE = 1;
    /**
     * <code>ALREADY_DONE = 2;</code>
     */
    public static final int ALREADY_DONE_VALUE = 2;
    /**
     * <code>RETRY = 3;</code>
     */
    public static final int RETRY_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static TRANSACTION_STATUS valueOf(int value) {
      return forNumber(value);
    }

    public static TRANSACTION_STATUS forNumber(int value) {
      switch (value) {
        case 0: return DONE;
        case 1: return DENIED;
        case 2: return ALREADY_DONE;
        case 3: return RETRY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TRANSACTION_STATUS>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        TRANSACTION_STATUS> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TRANSACTION_STATUS>() {
            public TRANSACTION_STATUS findValueByNumber(int number) {
              return TRANSACTION_STATUS.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.kion.bunga.domain.Proto.getDescriptor().getEnumTypes().get(0);
    }

    private static final TRANSACTION_STATUS[] VALUES = values();

    public static TRANSACTION_STATUS valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private TRANSACTION_STATUS(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.kion.bunga.domain.TRANSACTION_STATUS)
  }

  /**
   * Protobuf enum {@code com.kion.bunga.domain.TRANSACTION_TYPE}
   */
  public enum TRANSACTION_TYPE
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>IBAN_TO_IBAN = 0;</code>
     */
    IBAN_TO_IBAN(0),
    /**
     * <code>IBAN_TO_WALLET = 1;</code>
     */
    IBAN_TO_WALLET(1),
    /**
     * <code>WALLET_TO_IBAN = 2;</code>
     */
    WALLET_TO_IBAN(2),
    /**
     * <code>WALLET_TO_WALLET = 3;</code>
     */
    WALLET_TO_WALLET(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>IBAN_TO_IBAN = 0;</code>
     */
    public static final int IBAN_TO_IBAN_VALUE = 0;
    /**
     * <code>IBAN_TO_WALLET = 1;</code>
     */
    public static final int IBAN_TO_WALLET_VALUE = 1;
    /**
     * <code>WALLET_TO_IBAN = 2;</code>
     */
    public static final int WALLET_TO_IBAN_VALUE = 2;
    /**
     * <code>WALLET_TO_WALLET = 3;</code>
     */
    public static final int WALLET_TO_WALLET_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static TRANSACTION_TYPE valueOf(int value) {
      return forNumber(value);
    }

    public static TRANSACTION_TYPE forNumber(int value) {
      switch (value) {
        case 0: return IBAN_TO_IBAN;
        case 1: return IBAN_TO_WALLET;
        case 2: return WALLET_TO_IBAN;
        case 3: return WALLET_TO_WALLET;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TRANSACTION_TYPE>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        TRANSACTION_TYPE> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TRANSACTION_TYPE>() {
            public TRANSACTION_TYPE findValueByNumber(int number) {
              return TRANSACTION_TYPE.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.kion.bunga.domain.Proto.getDescriptor().getEnumTypes().get(1);
    }

    private static final TRANSACTION_TYPE[] VALUES = values();

    public static TRANSACTION_TYPE valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private TRANSACTION_TYPE(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.kion.bunga.domain.TRANSACTION_TYPE)
  }

  public interface PaymentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.kion.bunga.domain.Payment)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string sender = 1;</code>
     */
    java.lang.String getSender();
    /**
     * <code>string sender = 1;</code>
     */
    com.google.protobuf.ByteString
        getSenderBytes();

    /**
     * <code>string receiver = 2;</code>
     */
    java.lang.String getReceiver();
    /**
     * <code>string receiver = 2;</code>
     */
    com.google.protobuf.ByteString
        getReceiverBytes();

    /**
     * <code>int32 amount = 3;</code>
     */
    int getAmount();

    /**
     * <code>string uid = 4;</code>
     */
    java.lang.String getUid();
    /**
     * <code>string uid = 4;</code>
     */
    com.google.protobuf.ByteString
        getUidBytes();

    /**
     * <code>string name = 5;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 5;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string descripton = 6;</code>
     */
    java.lang.String getDescripton();
    /**
     * <code>string descripton = 6;</code>
     */
    com.google.protobuf.ByteString
        getDescriptonBytes();

    /**
     * <code>.com.kion.bunga.domain.TRANSACTION_TYPE transactionType = 7;</code>
     */
    int getTransactionTypeValue();
    /**
     * <code>.com.kion.bunga.domain.TRANSACTION_TYPE transactionType = 7;</code>
     */
    com.kion.bunga.domain.Proto.TRANSACTION_TYPE getTransactionType();
  }
  /**
   * Protobuf type {@code com.kion.bunga.domain.Payment}
   */
  public  static final class Payment extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.kion.bunga.domain.Payment)
      PaymentOrBuilder {
    // Use Payment.newBuilder() to construct.
    private Payment(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Payment() {
      sender_ = "";
      receiver_ = "";
      amount_ = 0;
      uid_ = "";
      name_ = "";
      descripton_ = "";
      transactionType_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Payment(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              sender_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              receiver_ = s;
              break;
            }
            case 24: {

              amount_ = input.readInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              uid_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              descripton_ = s;
              break;
            }
            case 56: {
              int rawValue = input.readEnum();

              transactionType_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kion.bunga.domain.Proto.internal_static_com_kion_bunga_domain_Payment_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kion.bunga.domain.Proto.internal_static_com_kion_bunga_domain_Payment_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kion.bunga.domain.Proto.Payment.class, com.kion.bunga.domain.Proto.Payment.Builder.class);
    }

    public static final int SENDER_FIELD_NUMBER = 1;
    private volatile java.lang.Object sender_;
    /**
     * <code>string sender = 1;</code>
     */
    public java.lang.String getSender() {
      java.lang.Object ref = sender_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sender_ = s;
        return s;
      }
    }
    /**
     * <code>string sender = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSenderBytes() {
      java.lang.Object ref = sender_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECEIVER_FIELD_NUMBER = 2;
    private volatile java.lang.Object receiver_;
    /**
     * <code>string receiver = 2;</code>
     */
    public java.lang.String getReceiver() {
      java.lang.Object ref = receiver_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        receiver_ = s;
        return s;
      }
    }
    /**
     * <code>string receiver = 2;</code>
     */
    public com.google.protobuf.ByteString
        getReceiverBytes() {
      java.lang.Object ref = receiver_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiver_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AMOUNT_FIELD_NUMBER = 3;
    private int amount_;
    /**
     * <code>int32 amount = 3;</code>
     */
    public int getAmount() {
      return amount_;
    }

    public static final int UID_FIELD_NUMBER = 4;
    private volatile java.lang.Object uid_;
    /**
     * <code>string uid = 4;</code>
     */
    public java.lang.String getUid() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uid_ = s;
        return s;
      }
    }
    /**
     * <code>string uid = 4;</code>
     */
    public com.google.protobuf.ByteString
        getUidBytes() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 5;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 5;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 5;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIPTON_FIELD_NUMBER = 6;
    private volatile java.lang.Object descripton_;
    /**
     * <code>string descripton = 6;</code>
     */
    public java.lang.String getDescripton() {
      java.lang.Object ref = descripton_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        descripton_ = s;
        return s;
      }
    }
    /**
     * <code>string descripton = 6;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptonBytes() {
      java.lang.Object ref = descripton_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        descripton_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRANSACTIONTYPE_FIELD_NUMBER = 7;
    private int transactionType_;
    /**
     * <code>.com.kion.bunga.domain.TRANSACTION_TYPE transactionType = 7;</code>
     */
    public int getTransactionTypeValue() {
      return transactionType_;
    }
    /**
     * <code>.com.kion.bunga.domain.TRANSACTION_TYPE transactionType = 7;</code>
     */
    public com.kion.bunga.domain.Proto.TRANSACTION_TYPE getTransactionType() {
      com.kion.bunga.domain.Proto.TRANSACTION_TYPE result = com.kion.bunga.domain.Proto.TRANSACTION_TYPE.valueOf(transactionType_);
      return result == null ? com.kion.bunga.domain.Proto.TRANSACTION_TYPE.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSenderBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sender_);
      }
      if (!getReceiverBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, receiver_);
      }
      if (amount_ != 0) {
        output.writeInt32(3, amount_);
      }
      if (!getUidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, uid_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, name_);
      }
      if (!getDescriptonBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, descripton_);
      }
      if (transactionType_ != com.kion.bunga.domain.Proto.TRANSACTION_TYPE.IBAN_TO_IBAN.getNumber()) {
        output.writeEnum(7, transactionType_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSenderBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sender_);
      }
      if (!getReceiverBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, receiver_);
      }
      if (amount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, amount_);
      }
      if (!getUidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, uid_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, name_);
      }
      if (!getDescriptonBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, descripton_);
      }
      if (transactionType_ != com.kion.bunga.domain.Proto.TRANSACTION_TYPE.IBAN_TO_IBAN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, transactionType_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.kion.bunga.domain.Proto.Payment)) {
        return super.equals(obj);
      }
      com.kion.bunga.domain.Proto.Payment other = (com.kion.bunga.domain.Proto.Payment) obj;

      boolean result = true;
      result = result && getSender()
          .equals(other.getSender());
      result = result && getReceiver()
          .equals(other.getReceiver());
      result = result && (getAmount()
          == other.getAmount());
      result = result && getUid()
          .equals(other.getUid());
      result = result && getName()
          .equals(other.getName());
      result = result && getDescripton()
          .equals(other.getDescripton());
      result = result && transactionType_ == other.transactionType_;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SENDER_FIELD_NUMBER;
      hash = (53 * hash) + getSender().hashCode();
      hash = (37 * hash) + RECEIVER_FIELD_NUMBER;
      hash = (53 * hash) + getReceiver().hashCode();
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getAmount();
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + getUid().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + DESCRIPTON_FIELD_NUMBER;
      hash = (53 * hash) + getDescripton().hashCode();
      hash = (37 * hash) + TRANSACTIONTYPE_FIELD_NUMBER;
      hash = (53 * hash) + transactionType_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.kion.bunga.domain.Proto.Payment parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kion.bunga.domain.Proto.Payment parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kion.bunga.domain.Proto.Payment parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kion.bunga.domain.Proto.Payment parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kion.bunga.domain.Proto.Payment parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kion.bunga.domain.Proto.Payment parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kion.bunga.domain.Proto.Payment parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.kion.bunga.domain.Proto.Payment parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kion.bunga.domain.Proto.Payment parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kion.bunga.domain.Proto.Payment parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.kion.bunga.domain.Proto.Payment prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.kion.bunga.domain.Payment}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.kion.bunga.domain.Payment)
        com.kion.bunga.domain.Proto.PaymentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kion.bunga.domain.Proto.internal_static_com_kion_bunga_domain_Payment_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kion.bunga.domain.Proto.internal_static_com_kion_bunga_domain_Payment_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kion.bunga.domain.Proto.Payment.class, com.kion.bunga.domain.Proto.Payment.Builder.class);
      }

      // Construct using com.kion.bunga.domain.Proto.Payment.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        sender_ = "";

        receiver_ = "";

        amount_ = 0;

        uid_ = "";

        name_ = "";

        descripton_ = "";

        transactionType_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kion.bunga.domain.Proto.internal_static_com_kion_bunga_domain_Payment_descriptor;
      }

      public com.kion.bunga.domain.Proto.Payment getDefaultInstanceForType() {
        return com.kion.bunga.domain.Proto.Payment.getDefaultInstance();
      }

      public com.kion.bunga.domain.Proto.Payment build() {
        com.kion.bunga.domain.Proto.Payment result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.kion.bunga.domain.Proto.Payment buildPartial() {
        com.kion.bunga.domain.Proto.Payment result = new com.kion.bunga.domain.Proto.Payment(this);
        result.sender_ = sender_;
        result.receiver_ = receiver_;
        result.amount_ = amount_;
        result.uid_ = uid_;
        result.name_ = name_;
        result.descripton_ = descripton_;
        result.transactionType_ = transactionType_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kion.bunga.domain.Proto.Payment) {
          return mergeFrom((com.kion.bunga.domain.Proto.Payment)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kion.bunga.domain.Proto.Payment other) {
        if (other == com.kion.bunga.domain.Proto.Payment.getDefaultInstance()) return this;
        if (!other.getSender().isEmpty()) {
          sender_ = other.sender_;
          onChanged();
        }
        if (!other.getReceiver().isEmpty()) {
          receiver_ = other.receiver_;
          onChanged();
        }
        if (other.getAmount() != 0) {
          setAmount(other.getAmount());
        }
        if (!other.getUid().isEmpty()) {
          uid_ = other.uid_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getDescripton().isEmpty()) {
          descripton_ = other.descripton_;
          onChanged();
        }
        if (other.transactionType_ != 0) {
          setTransactionTypeValue(other.getTransactionTypeValue());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kion.bunga.domain.Proto.Payment parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kion.bunga.domain.Proto.Payment) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object sender_ = "";
      /**
       * <code>string sender = 1;</code>
       */
      public java.lang.String getSender() {
        java.lang.Object ref = sender_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sender_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sender = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSenderBytes() {
        java.lang.Object ref = sender_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sender_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sender = 1;</code>
       */
      public Builder setSender(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sender_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sender = 1;</code>
       */
      public Builder clearSender() {
        
        sender_ = getDefaultInstance().getSender();
        onChanged();
        return this;
      }
      /**
       * <code>string sender = 1;</code>
       */
      public Builder setSenderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sender_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object receiver_ = "";
      /**
       * <code>string receiver = 2;</code>
       */
      public java.lang.String getReceiver() {
        java.lang.Object ref = receiver_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          receiver_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string receiver = 2;</code>
       */
      public com.google.protobuf.ByteString
          getReceiverBytes() {
        java.lang.Object ref = receiver_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          receiver_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string receiver = 2;</code>
       */
      public Builder setReceiver(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        receiver_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string receiver = 2;</code>
       */
      public Builder clearReceiver() {
        
        receiver_ = getDefaultInstance().getReceiver();
        onChanged();
        return this;
      }
      /**
       * <code>string receiver = 2;</code>
       */
      public Builder setReceiverBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        receiver_ = value;
        onChanged();
        return this;
      }

      private int amount_ ;
      /**
       * <code>int32 amount = 3;</code>
       */
      public int getAmount() {
        return amount_;
      }
      /**
       * <code>int32 amount = 3;</code>
       */
      public Builder setAmount(int value) {
        
        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 amount = 3;</code>
       */
      public Builder clearAmount() {
        
        amount_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object uid_ = "";
      /**
       * <code>string uid = 4;</code>
       */
      public java.lang.String getUid() {
        java.lang.Object ref = uid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string uid = 4;</code>
       */
      public com.google.protobuf.ByteString
          getUidBytes() {
        java.lang.Object ref = uid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string uid = 4;</code>
       */
      public Builder setUid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string uid = 4;</code>
       */
      public Builder clearUid() {
        
        uid_ = getDefaultInstance().getUid();
        onChanged();
        return this;
      }
      /**
       * <code>string uid = 4;</code>
       */
      public Builder setUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        uid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 5;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 5;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 5;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 5;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 5;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object descripton_ = "";
      /**
       * <code>string descripton = 6;</code>
       */
      public java.lang.String getDescripton() {
        java.lang.Object ref = descripton_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          descripton_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string descripton = 6;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptonBytes() {
        java.lang.Object ref = descripton_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          descripton_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string descripton = 6;</code>
       */
      public Builder setDescripton(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        descripton_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string descripton = 6;</code>
       */
      public Builder clearDescripton() {
        
        descripton_ = getDefaultInstance().getDescripton();
        onChanged();
        return this;
      }
      /**
       * <code>string descripton = 6;</code>
       */
      public Builder setDescriptonBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        descripton_ = value;
        onChanged();
        return this;
      }

      private int transactionType_ = 0;
      /**
       * <code>.com.kion.bunga.domain.TRANSACTION_TYPE transactionType = 7;</code>
       */
      public int getTransactionTypeValue() {
        return transactionType_;
      }
      /**
       * <code>.com.kion.bunga.domain.TRANSACTION_TYPE transactionType = 7;</code>
       */
      public Builder setTransactionTypeValue(int value) {
        transactionType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.kion.bunga.domain.TRANSACTION_TYPE transactionType = 7;</code>
       */
      public com.kion.bunga.domain.Proto.TRANSACTION_TYPE getTransactionType() {
        com.kion.bunga.domain.Proto.TRANSACTION_TYPE result = com.kion.bunga.domain.Proto.TRANSACTION_TYPE.valueOf(transactionType_);
        return result == null ? com.kion.bunga.domain.Proto.TRANSACTION_TYPE.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.kion.bunga.domain.TRANSACTION_TYPE transactionType = 7;</code>
       */
      public Builder setTransactionType(com.kion.bunga.domain.Proto.TRANSACTION_TYPE value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        transactionType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.kion.bunga.domain.TRANSACTION_TYPE transactionType = 7;</code>
       */
      public Builder clearTransactionType() {
        
        transactionType_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.kion.bunga.domain.Payment)
    }

    // @@protoc_insertion_point(class_scope:com.kion.bunga.domain.Payment)
    private static final com.kion.bunga.domain.Proto.Payment DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.kion.bunga.domain.Proto.Payment();
    }

    public static com.kion.bunga.domain.Proto.Payment getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Payment>
        PARSER = new com.google.protobuf.AbstractParser<Payment>() {
      public Payment parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Payment(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Payment> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Payment> getParserForType() {
      return PARSER;
    }

    public com.kion.bunga.domain.Proto.Payment getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TransactionResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.kion.bunga.domain.TransactionResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.kion.bunga.domain.TRANSACTION_STATUS status = 1;</code>
     */
    int getStatusValue();
    /**
     * <code>.com.kion.bunga.domain.TRANSACTION_STATUS status = 1;</code>
     */
    com.kion.bunga.domain.Proto.TRANSACTION_STATUS getStatus();

    /**
     * <code>string message = 2;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 2;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code com.kion.bunga.domain.TransactionResponse}
   */
  public  static final class TransactionResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.kion.bunga.domain.TransactionResponse)
      TransactionResponseOrBuilder {
    // Use TransactionResponse.newBuilder() to construct.
    private TransactionResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TransactionResponse() {
      status_ = 0;
      message_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private TransactionResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              status_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kion.bunga.domain.Proto.internal_static_com_kion_bunga_domain_TransactionResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kion.bunga.domain.Proto.internal_static_com_kion_bunga_domain_TransactionResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kion.bunga.domain.Proto.TransactionResponse.class, com.kion.bunga.domain.Proto.TransactionResponse.Builder.class);
    }

    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_;
    /**
     * <code>.com.kion.bunga.domain.TRANSACTION_STATUS status = 1;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.com.kion.bunga.domain.TRANSACTION_STATUS status = 1;</code>
     */
    public com.kion.bunga.domain.Proto.TRANSACTION_STATUS getStatus() {
      com.kion.bunga.domain.Proto.TRANSACTION_STATUS result = com.kion.bunga.domain.Proto.TRANSACTION_STATUS.valueOf(status_);
      return result == null ? com.kion.bunga.domain.Proto.TRANSACTION_STATUS.UNRECOGNIZED : result;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private volatile java.lang.Object message_;
    /**
     * <code>string message = 2;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (status_ != com.kion.bunga.domain.Proto.TRANSACTION_STATUS.DONE.getNumber()) {
        output.writeEnum(1, status_);
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (status_ != com.kion.bunga.domain.Proto.TRANSACTION_STATUS.DONE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, status_);
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.kion.bunga.domain.Proto.TransactionResponse)) {
        return super.equals(obj);
      }
      com.kion.bunga.domain.Proto.TransactionResponse other = (com.kion.bunga.domain.Proto.TransactionResponse) obj;

      boolean result = true;
      result = result && status_ == other.status_;
      result = result && getMessage()
          .equals(other.getMessage());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.kion.bunga.domain.Proto.TransactionResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kion.bunga.domain.Proto.TransactionResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kion.bunga.domain.Proto.TransactionResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kion.bunga.domain.Proto.TransactionResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kion.bunga.domain.Proto.TransactionResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kion.bunga.domain.Proto.TransactionResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kion.bunga.domain.Proto.TransactionResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.kion.bunga.domain.Proto.TransactionResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kion.bunga.domain.Proto.TransactionResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kion.bunga.domain.Proto.TransactionResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.kion.bunga.domain.Proto.TransactionResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.kion.bunga.domain.TransactionResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.kion.bunga.domain.TransactionResponse)
        com.kion.bunga.domain.Proto.TransactionResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kion.bunga.domain.Proto.internal_static_com_kion_bunga_domain_TransactionResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kion.bunga.domain.Proto.internal_static_com_kion_bunga_domain_TransactionResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kion.bunga.domain.Proto.TransactionResponse.class, com.kion.bunga.domain.Proto.TransactionResponse.Builder.class);
      }

      // Construct using com.kion.bunga.domain.Proto.TransactionResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        status_ = 0;

        message_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kion.bunga.domain.Proto.internal_static_com_kion_bunga_domain_TransactionResponse_descriptor;
      }

      public com.kion.bunga.domain.Proto.TransactionResponse getDefaultInstanceForType() {
        return com.kion.bunga.domain.Proto.TransactionResponse.getDefaultInstance();
      }

      public com.kion.bunga.domain.Proto.TransactionResponse build() {
        com.kion.bunga.domain.Proto.TransactionResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.kion.bunga.domain.Proto.TransactionResponse buildPartial() {
        com.kion.bunga.domain.Proto.TransactionResponse result = new com.kion.bunga.domain.Proto.TransactionResponse(this);
        result.status_ = status_;
        result.message_ = message_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kion.bunga.domain.Proto.TransactionResponse) {
          return mergeFrom((com.kion.bunga.domain.Proto.TransactionResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kion.bunga.domain.Proto.TransactionResponse other) {
        if (other == com.kion.bunga.domain.Proto.TransactionResponse.getDefaultInstance()) return this;
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kion.bunga.domain.Proto.TransactionResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kion.bunga.domain.Proto.TransactionResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int status_ = 0;
      /**
       * <code>.com.kion.bunga.domain.TRANSACTION_STATUS status = 1;</code>
       */
      public int getStatusValue() {
        return status_;
      }
      /**
       * <code>.com.kion.bunga.domain.TRANSACTION_STATUS status = 1;</code>
       */
      public Builder setStatusValue(int value) {
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.kion.bunga.domain.TRANSACTION_STATUS status = 1;</code>
       */
      public com.kion.bunga.domain.Proto.TRANSACTION_STATUS getStatus() {
        com.kion.bunga.domain.Proto.TRANSACTION_STATUS result = com.kion.bunga.domain.Proto.TRANSACTION_STATUS.valueOf(status_);
        return result == null ? com.kion.bunga.domain.Proto.TRANSACTION_STATUS.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.kion.bunga.domain.TRANSACTION_STATUS status = 1;</code>
       */
      public Builder setStatus(com.kion.bunga.domain.Proto.TRANSACTION_STATUS value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.kion.bunga.domain.TRANSACTION_STATUS status = 1;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>string message = 2;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.kion.bunga.domain.TransactionResponse)
    }

    // @@protoc_insertion_point(class_scope:com.kion.bunga.domain.TransactionResponse)
    private static final com.kion.bunga.domain.Proto.TransactionResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.kion.bunga.domain.Proto.TransactionResponse();
    }

    public static com.kion.bunga.domain.Proto.TransactionResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TransactionResponse>
        PARSER = new com.google.protobuf.AbstractParser<TransactionResponse>() {
      public TransactionResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TransactionResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TransactionResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TransactionResponse> getParserForType() {
      return PARSER;
    }

    public com.kion.bunga.domain.Proto.TransactionResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kion_bunga_domain_Payment_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_kion_bunga_domain_Payment_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_kion_bunga_domain_TransactionResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_kion_bunga_domain_TransactionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014schema.proto\022\025com.kion.bunga.domain\"\254\001" +
      "\n\007Payment\022\016\n\006sender\030\001 \001(\t\022\020\n\010receiver\030\002 " +
      "\001(\t\022\016\n\006amount\030\003 \001(\005\022\013\n\003uid\030\004 \001(\t\022\014\n\004name" +
      "\030\005 \001(\t\022\022\n\ndescripton\030\006 \001(\t\022@\n\017transactio" +
      "nType\030\007 \001(\0162\'.com.kion.bunga.domain.TRAN" +
      "SACTION_TYPE\"a\n\023TransactionResponse\0229\n\006s" +
      "tatus\030\001 \001(\0162).com.kion.bunga.domain.TRAN" +
      "SACTION_STATUS\022\017\n\007message\030\002 \001(\t*G\n\022TRANS" +
      "ACTION_STATUS\022\010\n\004DONE\020\000\022\n\n\006DENIED\020\001\022\020\n\014A" +
      "LREADY_DONE\020\002\022\t\n\005RETRY\020\003*b\n\020TRANSACTION_",
      "TYPE\022\020\n\014IBAN_TO_IBAN\020\000\022\022\n\016IBAN_TO_WALLET" +
      "\020\001\022\022\n\016WALLET_TO_IBAN\020\002\022\024\n\020WALLET_TO_WALL" +
      "ET\020\003B!\n\025com.kion.bunga.domainB\005Proto\210\001\001b" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_kion_bunga_domain_Payment_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_kion_bunga_domain_Payment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_kion_bunga_domain_Payment_descriptor,
        new java.lang.String[] { "Sender", "Receiver", "Amount", "Uid", "Name", "Descripton", "TransactionType", });
    internal_static_com_kion_bunga_domain_TransactionResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_kion_bunga_domain_TransactionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_kion_bunga_domain_TransactionResponse_descriptor,
        new java.lang.String[] { "Status", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
